// AUTO MAINTAINED FILE: DO NOT CHANGE

export const GET_INIT_DATA_BEGIN = 'GET_INIT_DATA_BEGIN';
export const GET_INIT_DATA_SUCCESS = 'GET_INIT_DATA_SUCCESS';
export const GET_INIT_DATA_FAILURE = 'GET_INIT_DATA_FAILURE';
export const GET_INIT_DATA_DISMISS_ERROR = 'GET_INIT_DATA_DISMISS_ERROR';
export const RUN_CMD = 'RUN_CMD';
export const STOP_CMD = 'STOP_CMD';
export const SAVE_CMD_BEGIN = 'SAVE_CMD_BEGIN';
export const SAVE_CMD_SUCCESS = 'SAVE_CMD_SUCCESS';
export const SAVE_CMD_FAILURE = 'SAVE_CMD_FAILURE';
export const SAVE_CMD_DISMISS_ERROR = 'SAVE_CMD_DISMISS_ERROR';
export const DELETE_CMD_BEGIN = 'DELETE_CMD_BEGIN';
export const DELETE_CMD_SUCCESS = 'DELETE_CMD_SUCCESS';
export const DELETE_CMD_FAILURE = 'DELETE_CMD_FAILURE';
export const DELETE_CMD_DISMISS_ERROR = 'DELETE_CMD_DISMISS_ERROR';
export const REORDER_CMDS_BEGIN = 'REORDER_CMDS_BEGIN';
export const REORDER_CMDS_SUCCESS = 'REORDER_CMDS_SUCCESS';
export const REORDER_CMDS_FAILURE = 'REORDER_CMDS_FAILURE';
export const REORDER_CMDS_DISMISS_ERROR = 'REORDER_CMDS_DISMISS_ERROR';
