// AUTO MAINTAINED FILE: DO NOT CHANGE

export const GET_INIT_DATA_BEGIN = 'GET_INIT_DATA_BEGIN';
export const GET_INIT_DATA_SUCCESS = 'GET_INIT_DATA_SUCCESS';
export const GET_INIT_DATA_FAILURE = 'GET_INIT_DATA_FAILURE';
export const GET_INIT_DATA_DISMISS_ERROR = 'GET_INIT_DATA_DISMISS_ERROR';
export const RUN_CMD = 'RUN_CMD';
export const STOP_CMD = 'STOP_CMD';
